name: database
containers:
- image: mariadb:10
  env:
  - name: MYSQL_ROOT_PASSWORD
    value: rootpasswd
  - name: MYSQL_DATABASE
    valueFrom:
      configMapKeyRef:
        key: MYSQL_DATABASE
        name: database
  - name: MYSQL_USER
    value: wordpress
  - name: MYSQL_PASSWORD
    value: wordpress
  volumeMounts:
  - name: database
    mountPath: /var/lib/mysql
  livenessProbe:
    exec:
      command:
      - mysqladmin
      - ping
    initialDelaySeconds: 30
    timeoutSeconds: 5
  readinessProbe:
    exec:
      command:
      - mysqladmin
      - ping
    initialDelaySeconds: 5
    timeoutSeconds: 1
services:
- name: database
  ports:
  - port: 3306
configData:
  MYSQL_DATABASE: wordpress
